### ISSUE TITLE
Add animation options to FlowComponent transition() function

### ISSUE THREAD

**Issue by nvh** [koenbok/Framer#472]
Currently it's only possible to define animation options inside of the states that you define inside your custom transition function like this: https://github.com/koenbok/Framer/blob/6d8bc7eb22fb4c604330aa02946e7a5ee8eff907/framer/Components/FlowComponent.coffee#L440

But it would be cool if it was possible to pass them to `flow.transition()` as well. We already add the ability to pass `animate` and `scroll` options, but maybe we could add an `animationOptions` to  the options object, or maybe just add the options to the animation options

Example:

```
# Custom transition 
scaleTransition = (nav, layerA, layerB, overlay) ->
    transition =
        layerA:
            show:
                scale: 1.0
                opacity: 1
            hide:
                scale: 0.5
                opacity: 0
        layerB:
            show:
                scale: 1.0
                opacity: 1
            hide:
                scale: 0.5
                opacity: 0
 
# Create layers 
layerA = new Layer
    backgroundColor: "#00AAFF"
    size: Screen.size
 
layerB = new Layer
    backgroundColor: "#FFCC33"
    size: Screen.size
 
# Create FlowComponent 
flow = new FlowComponent
flow.showNext(layerA)
 
# Switch to layerB with custom transition 
layerA.onClick ->
    flow.transition(layerB, scaleTransition, {time: 0.1, scroll: false})
```
