### ISSUE TITLE
Layer border in v90

### ISSUE THREAD

**Issue by d4rekanguok** [koenbok/Framer#505]
The wiki page on today's new update states that Framer now support border per side, however I haven't been able to get this to work with the code below:

```
layerA = new Layer
    border:
        left: 1
        right: 1
        bottom: 0
        top: 0
```
Please let me know if I'm missing something
